---

- name: Update apt cache
  apt:
    update_cache: yes
  register: apt_action
  retries: 10
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)


- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
  register: apt_action
  retries: 10
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)


- name: Upgrade the OS (apt-get dist-upgrade)
  apt:
    upgrade: dist
  register: apt_action
  retries: 10
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)


- name: Install a common list of packages
  apt:
    pkg:
    - ca-certificates
    - tree
    - wget
    - curl
    - unzip
    state: present
  register: apt_action
  retries: 10
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Change the hostname
  hostname:
    name="{{ hostname }}"
  when:
    ansible_fqdn != fqdn

- name: Fix /etc/hosts removing the old hostname
  tags:
    - hosts
  lineinfile:
    state=present
    dest=/etc/hosts
    line="{{ ansible_host }} {{ hostname }} {{ fqdn }}"
    regexp="^{{ ansible_host }}"
  when:
    ansible_fqdn != fqdn